image:
  file: .gitpod.Dockerfile
tasks:
  - name: "building project to load dependencies"
    init: |
      cd yew-app
      trunk build
  - name: "serving app"
    command: |
      cd yew-app
      trunk serve
ports:
  - port: 8000
    onOpen: open-preview